### ISSUE TITLE
Reported FIDs do not match DDIM

### ISSUE THREAD

**Issue by nfrumkin** [42Shawn/PTQ4DM#2]
In an effort to avoid wasting time, please note that the reported FID scores for DDIM in this paper do not match prior work. I would recommend using some other repository which can reproduce the baseline.

Do you (authors) have a good explanation for this? Perhaps, I am missing something.

**Comment by 42Shawn** [comment]
As we mentioned in the experimental setting part of our paper, we do not strictly reproduce DDIM. The number of samples that we generate is only 10,000 (50,000 in several papers) in order to efficiently compare our methods with other baselines quantitatively. Thus some reported results in this paper are slightly different from the results in the original papers. 

The trend between different quantization methods is more important for us. Also, all the results reported in this paper can be reproduced using this repo.

**Comment by yuzheyao22** [comment]
Thank you for you awesome work! When testing the w8a8 quantizated model on cifar10, I can not reproduce the same FID score as claimed in the paper. I suppose maybe I did not use the optimal hyper parameters. Could you please provide the hyper parameter which allow the w8a8 model to get a FID score of 14 on the cifar10? Thank you in advance

**Comment by JiaojiaoYe1994** [comment]
> In an effort to avoid wasting time, please note that the reported FID scores for DDIM in this paper do not match prior work. I would recommend using some other repository which can reproduce the baseline.
> 
> Do you (authors) have a good explanation for this? Perhaps, I am missing something.

Hello, I have generated sample `.npz` file using provided bash shell, could you provide tell me how do you calculate FID?

**Comment by yuzheyao22** [comment]
> > In an effort to avoid wasting time, please note that the reported FID scores for DDIM in this paper do not match prior work. I would recommend using some other repository which can reproduce the baseline.
> > Do you (authors) have a good explanation for this? Perhaps, I am missing something.
> 
> Hello, I have generated sample `.npz` file using provided bash shell, could you provide tell me how do you calculate FID?

Hi, you can use the evaluator provided in directory "guided-diffusion", or use module provided here: https://github.com/mseitzer/pytorch-fid/
